kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: meatbox-dev-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  selector:
    matchLabels:
      name: meatbox-dev-pv
